CrmSys/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from app_stark.service.StarkModular import site
from crm.views import Login, Logout, Welcome, NoPermissionHtml

urlpatterns = [
    # path('admin/', admin.site.urls),
    # popup 测试代码
    # path('', Index.as_view(), name='index'),
    # path('add/city/', AddCity.as_view(), name='add_city'),

    # 用户登陆&退出
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('welcome/', Welcome.as_view(), name='welcome'),
    path('no_permission_html/', NoPermissionHtml.as_view()),
    # stark 组件应用
    path('stark/', site.urls),
    # rbac 组件应用
    path('rbac/', include('app_rbac.urls', namespace='rbac')),

]

app_rbac/service/urls.py
from django.urls import reverse
from django.http import QueryDict


def memoryUrl(request, name, *args, **kwargs):
    """
    生成带有原搜索条件的url，替代模版中的url(url携带参数)
    :param request:
    :param name:
    :return:
    """
    basicUrl = reverse(name, args=args, kwargs=kwargs)
    if not request.GET:  # 当前url中无参数直接返回默认url
        return basicUrl
    queryDict = QueryDict(mutable=True)
    queryDict['_filter'] = request.GET.urlencode()
    oldSearchUrl = queryDict.urlencode()  # 打包（转义）
    return "%s?%s" % (basicUrl, oldSearchUrl)


def memoryReverse(request, name, *args, **kwargs):
    """
    反向生成URL跳转回原地址：
        1.将原来的URL中的搜索条件获取到 _filter
        2.通过reverse生成原来的URL
    将menu操作中的生成url方法封装在此，便于多次调用
    :param request: request
    :param name:  reverse参数
    :param args:  编辑和修改需要的ID
    :param kwargs:  同上
    :return:  返回一个携带参数的url跳转链接
    """
    url = reverse(name, args=args, kwargs=kwargs)
    originParams = request.GET.get('_filter')
    return "%s?%s" % (url, originParams) if originParams else url

app_rbac/urls.py
from django.urls import path, re_path
from app_rbac.views import role  # 角色
from app_rbac.views import user  # 用户
from app_rbac.views import menu  # 菜单

app_name = 'rbac'
urlpatterns = [
    # 角色管理
    path('role/list/', role.RoleList.as_view(), name='role_list'),
    path('role/add/', role.RoleAdd.as_view(), name='role_add'),
    re_path(r'role/edit/(?P<pk>\d+)/$', role.RoleEdit.as_view(), name='role_edit'),
    re_path(r'role/del/(?P<pk>\d+)/$', role.RoleDel.as_view(), name='role_del'),
    # 用户管理
    path('user/list/', user.UserList.as_view(), name='user_list'),
    path('user/add/', user.UserAdd.as_view(), name='user_add'),
    re_path(r'user/edit/(?P<pk>\d+)/$', user.UserEdit.as_view(), name='user_edit'),
    re_path(r'user/del/(?P<pk>\d+)/$', user.UserDel.as_view(), name='user_del'),
    re_path(r'user/reset/(?P<pk>\d+)$', user.ResetPassword.as_view(), name='user_reset'),
    # 一级菜单管理
    path('menu/list/', menu.MenuList.as_view(), name='menu_list'),
    path('menu/add/', menu.MenuAdd.as_view(), name='menu_add'),
    re_path(r'menu/edit/(?P<pk>\d+)/$', menu.MenuEdit.as_view(), name='menu_edit'),
    re_path(r'menu/del/(?P<pk>\d+)/$', menu.MenuDel.as_view(), name='menu_del'),
    # 二级菜单管理
    re_path(r'second/menu/add/(?P<menuId>\d+)/$', menu.SecondMenuAdd.as_view(), name='second_menu_add'),
    re_path(r'second/menu/edit(?P<pk>\d+)/$', menu.second_menu_edit, name='second_menu_edit'),
    re_path(r'second/menu/del(?P<pk>\d+)/$', menu.second_menu_del, name='second_menu_del'),
    # 权限管理
    re_path(r'permission/add/(?P<secondMenuId>\d+)/$', menu.PermissionAdd.as_view(), name='permission_add'),
    re_path(r'permission/edit/(?P<pk>\d+)/$', menu.permission_edit, name='permission_edit'),
    re_path(r'permission/del/(?P<pk>\d+)/$', menu.permission_del, name='permission_del'),
    # 批量操作权限
    path('multi/permissions/', menu.multi_permissions, name='multi_permissions'),
    re_path(r'^multi/permissions/del/(?P<pk>\d+)/$', menu.multi_permissions_del, name='multi_permissions_del'),
    # 权限分配
    path('distribute/permissions/', menu.distribute_permissions, name='distribute_permissions')
]

app_rbac/forms/base.py
from django import forms


class BootStrapModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        """
        统一添加样式,使用的时候直接在form类中继承这个类即可，因为这个类已经继承了一个 forms.ModelForm 这个基类，
        再次继承这个类的话也会继承这个基类，并且同时继承了这个类的所有方法
        :param args:
        :param kwargs:
        """
        super(BootStrapModelForm, self).__init__(*args, **kwargs)
        for name, fields in self.fields.items():
            fields.widget.attrs['class'] = 'form-control'

app_rbac/forms/role.py
from django import forms
from app_rbac.models import Role


class RoleModelForm(forms.ModelForm):
    class Meta:
        model = Role
        fields = ['title']  # 如果直接写成  '__all__'， 表示对所有字段都可以进行操作
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'})
        }

app_rbac/service/routes.py
from collections import OrderedDict
from django.conf import settings as sys
from django.utils.module_loading import import_string  # 内置工具，根据字符串进行导入模块
from django.urls import URLResolver, URLPattern
import re

"""
自动发现项目中的url方法
"""


class AutoFindUrl:
    def check_url_exclude(self, url):
        """
        白名单设置;排除一些特定的url的查找
        :param url:
        :return:
        """
        for regex in sys.AUTO_DISCOVER_EXCLUDE:
            if re.match(regex, url):
                return True

    def recursion_urls(self, pre_namespace, pre_url, url_patterns, url_ordered_dict):
        """
        :param pre_namespace: namespace的前缀， 以后用于拼接name
        :param pre_url: url的前缀， 以后用于拼接url
        :param url_patterns: 用于循环的路由， 路由关系列表
        :param url_ordered_dict: 用于保存递归中获取的所有路由，有序字典
        :return:
        """
        for item in url_patterns:
            if isinstance(item, URLPattern):  # 非路由分发
                if not item.name:
                    continue
                name = item.name if not pre_namespace else "%s:%s" % (pre_namespace, item.name)
                url = pre_url + item.pattern.regex.pattern
                url = url.replace('^', '').replace('$', '')
                if self.check_url_exclude(url):
                    continue
                url_ordered_dict[name] = {'name': name, 'url': url}
            elif isinstance(item, URLResolver):  # 路由分发, 递归
                if pre_namespace:
                    namespace = "%s:%s" % (pre_namespace, item.namespace) if item.namespace else item.namespace
                else:
                    namespace = item.namespace if item.namespace else None
                self.recursion_urls(namespace, pre_url + item.pattern.regex.pattern, item.url_patterns, url_ordered_dict)

    def get_all_url_dict(self):
        """
        自动发现项目中的URL(必须有  name  别名)
        :return: 所有url的有序字典
        """
        url_ordered_dict = OrderedDict()  # {'rbac:menu_list': {name:'rbac:menu_list', url: 'xxx/xxx/menu_list'}}
        md = import_string(sys.ROOT_URLCONF)  # 根据字符串的形式去导入一个模块，在settings中 ROOT_URLCONF 指向的就是项目根路由的文件地址
        self.recursion_urls(None, '/', md.urlpatterns, url_ordered_dict)
        return url_ordered_dict

app_rbac/views/menu.py
from django.shortcuts import render, redirect, HttpResponse
from django.views import View
from django.utils.module_loading import import_string
from django.forms import formset_factory
from CrmSys import settings as sys
from collections import OrderedDict

from app_rbac import models
from app_rbac.forms.menu import MenuModelForm, \
    SecondMenuModelForm, PermissionModelForm, \
    MultiAddPermissionForm, \
    MultiEditPermissionForm
from app_rbac.models import *
from app_rbac.service.MemoryUrls import memoryReverse
from app_rbac.service.AutoFindUrls import AutoFindUrl

"""
一级菜单管理
"""


class MenuList(View):
    """
    所有菜单
    """

    def get(self, request):
        menu = Menu.objects.all()
        menuId = request.GET.get('mid')  # 用户选择的一级菜单
        secondMenuId = request.GET.get('sid')  # 用户选择的二级菜单
        # get方法拿到的mid是字符串类型，前端页面做判断的时候从数据库中取出的id是整型

        # 在没有选中一级菜单的情况下是否展示新增按钮：
        menu_exists = Menu.objects.filter(id=menuId).exists()
        if not menu_exists:
            menuId = None

        if menuId:
            secondMenus = Permission.objects.filter(menu_id=menuId)  # 根据选择的一级菜单获取倒二级菜单
        else:
            secondMenus = []

        # 在没有选中二级菜单的情况下是否展示新增按钮：
        second_menu_exists = Permission.objects.filter(id=secondMenuId).exists()
        if not second_menu_exists:
            secondMenuId = None
        if secondMenuId:
            permissions = Permission.objects.filter(pid=secondMenuId)  # 根据选择的二级菜单查询到对应的所有权限
        else:
            permissions = []

        return render(request, 'rbac/menu_list.html', locals())

    def post(self, request):
        pass


class MenuAdd(View):
    """
    添加一级菜单
    """

    def get(self, request):
        form = MenuModelForm
        return render(request, 'rbac/change.html', locals())

    def post(self, request):
        form = MenuModelForm(data=request.POST)
        if form.is_valid():
            form.save()
            url = memoryReverse(request, 'rbac:menu_list')
            return redirect(url)
        else:
            return render(request, 'rbac/change.html', locals())


class MenuEdit(View):
    """
    菜单修改
    """

    def get(self, request, pk):
        menuObj = Menu.objects.filter(id=pk).first()
        if not menuObj:
            return HttpResponse('禁止操作!')  # 角色不存在
        form = MenuModelForm(instance=menuObj)
        return render(request, 'rbac/change.html', locals())

    def post(self, request, pk):
        menuObj = Menu.objects.filter(id=pk).first()
        form = MenuModelForm(instance=menuObj, data=request.POST)
        if form.is_valid():
            form.save()
            url = memoryReverse(request, 'rbac:menu_list')
            return redirect(url)


class MenuDel(View):
    """
    菜单删除
    """

    def get(self, request, pk):
        url = memoryReverse(request, 'rbac:menu_list')
        return render(request, 'rbac/delete.html', {'cancelUrl': url})

    def post(self, request, pk):
        Menu.objects.filter(id=pk).delete()  # 删除
        # 拼接出原搜索条件url，进行跳转
        url = memoryReverse(request, 'rbac:menu_list')
        return redirect(url)


"""
二级菜单管理
"""


class SecondMenuAdd(View):

    def get(self, request, menuId):
        """
        二级菜单的添加
        :param request:
        :param menuId: 默认的一级菜单ID(用于设置默认值)
        :return:
        """
        menuObj = Menu.objects.filter(id=menuId).first()
        form = SecondMenuModelForm(initial={'menu': menuObj})
        return render(request, 'rbac/change.html', locals())

    def post(self, request, menuId):
        form = SecondMenuModelForm(data=request.POST)
        if form.is_valid():
            form.save()
            url = memoryReverse(request, 'rbac:menu_list')
            return redirect(url)
        else:
            return render(request, 'rbac/change.html', locals())


def second_menu_edit(request, pk):
    permissionObj = Permission.objects.filter(id=pk).first()
    if request.method == 'GET':
        form = SecondMenuModelForm(instance=permissionObj)
        return render(request, 'rbac/change.html', locals())

    form = SecondMenuModelForm(data=request.POST, instance=permissionObj)
    if form.is_valid():
        form.save()
        return redirect(memoryReverse(request, 'rbac:menu_list'))
    return render(request, 'rbac/change.html', locals())


def second_menu_del(request, pk):
    url = memoryReverse(request, 'rbac:menu_list')
    if request.method == 'GET':
        return render(request, 'rbac/delete.html', {'cancelUrl': url})

    models.Permission.objects.filter(id=pk).delete()
    return redirect(url)


"""
权限管理
"""


class PermissionAdd(View):
    """
    添加权限
    """

    def get(self, request, secondMenuId):
        # menuObj = Menu.objects.filter(id=menuId).first()
        form = PermissionModelForm()
        return render(request, 'rbac/change.html', locals())

    def post(self, request, secondMenuId):
        form = PermissionModelForm(data=request.POST)
        if form.is_valid():
            secondMenuObj = Permission.objects.filter(id=secondMenuId).first()
            if not secondMenuObj:
                return HttpResponse('当前二级菜单不存在，请重新选择二级菜单！')
            # form.instance中：包含了用户提交的所有值
            form.instance.pid = secondMenuObj
            """
             ↑ 这句话相当于执行了三次操作
            - instance = Permission(title='用户输入值', url='用户输入', name='用户输入')
            - instance.pid = secondMenuObj
            - instance.save()
            form.save()
            其实就是保存数据倒数据库中， 表单收集倒的用户输入的数据已经被实例化为了一个对象 ————> instance
            """
            form.save()
            url = memoryReverse(request, 'rbac:menu_list')
            return redirect(url)
        else:
            return render(request, 'rbac/change.html', locals())


def permission_edit(request, pk):
    """
    编辑权限
    :param request:
    :param pk: 当前编辑的权限的pk
    :return:
    """
    permissionObj = Permission.objects.filter(id=pk).first()
    if request.method == 'GET':
        form = PermissionModelForm(instance=permissionObj)
        return render(request, 'rbac/change.html', locals())
    form = PermissionModelForm(data=request.POST, instance=permissionObj)
    if form.is_valid():
        form.save()
        return redirect(memoryReverse(request, 'rbac:menu_list'))
    return render(request, 'rbac/change.html', locals())


class PermissionEdit(View):
    """
    类方法实现编辑当前权限路由
    """

    def get(self, request, pk):
        permissionObj = models.Permission.objects.filter(id=pk).first()
        form = PermissionModelForm(instance=permissionObj)
        return render(request, 'rbac/change.html', locals())

    def post(self, request, pk):
        permissionObj = models.Permission.objects.filter(id=pk).first()
        form = PermissionModelForm(instance=permissionObj)
        if form.is_valid():
            form.save()
            return redirect(memoryReverse(request, 'rbac:menu_list'))


def permission_del(request, pk):
    """
    删除权限路由
    :param request:
    :param pk: 当前删除的权限pk
    :return:
    """
    url = memoryReverse(request, 'rbac:menu_list')
    if request.method == 'GET':
        return render(request, 'rbac/delete.html', {'cancelUrl': url})
    Permission.objects.filter(id=pk).delete()
    return redirect(url)


class PermissionDel(View):
    """
    类方法删除当前权限信息
    """

    def get(self, request):
        url = memoryReverse(request, 'rbac:menu_list')
        return render(request, 'rbac/delete.html', {'cancelUrl': url})

    def post(self, request, pk):
        url = memoryReverse(request, 'rbac:menu_list')
        models.Permission.objects.filter(id=pk).delete()
        return redirect(url)


"""
    权限的批量操作
"""


def multi_permissions(request):
    post_type = request.GET.get('type')
    generate_formset_class = formset_factory(MultiAddPermissionForm, extra=0)  # 批量添加的表单类
    generate_formset = None
    update_formset = None
    update_formset_class = formset_factory(MultiEditPermissionForm, extra=0)  # 批量更新的表单类
    if request.method == 'POST' and post_type == 'generate':
        # 批量添加
        formset = generate_formset_class(data=request.POST)
        if formset.is_valid():
            object_list = []  # 要添加的数据
            post_row_list = formset.cleaned_data
            has_error = False
            for i in range(0, formset.total_form_count()):
                row_dict = post_row_list[i]
                try:
                    new_obj = Permission(**row_dict)
                    new_obj.validate_unique()
                    object_list.append(new_obj)  # 检测通过直接append到批量添加的数据中然后批量添加
                except Exception as e:
                    has_error = True
                    formset.errors[i].update(e)
                    generate_formset = formset
            if not has_error:
                Permission.objects.bulk_create(object_list, batch_size=100)  # 没有错误信息的时候直接批量添加操作
        else:
            generate_formset = formset

    if request.method == 'POST' and post_type == 'update':
        # 批量更新
        formset = update_formset_class(data=request.POST)
        if formset.is_valid():
            post_row_list = formset.cleaned_data
            for i in range(0, formset.total_form_count()):
                row_dict = post_row_list[i]
                permission_id = row_dict.pop('id')
                try:
                    row_obj = Permission.objects.filter(id=permission_id).first()
                    for k, v in row_dict.items():
                        setattr(row_obj, k, v)
                    row_obj.validate_unique()  # 唯一性检查
                    row_obj.save()
                except Exception as e:
                    formset.errors[i].update(e)
                    update_formset = formset
        else:
            update_formset = formset

    # 1.获取项目中的url集合 - set()
    auto_find_url = AutoFindUrl()
    all_url = auto_find_url.get_all_url_dict()
    router_name_set = set(all_url.keys())

    # 2.获取数据库中的url集合 - set()
    permission = Permission.objects.all().values('id', 'title', 'name', 'url', 'menu_id', 'pid_id')

app_rbac/templates/rbac/breadcrumb.html
<!-- 菜单路径导航 -->
<div>
    <ol class="breadcrumb no-radius no-margin" style="border-bottom: 1px solid #ddd;">
        {% for item in recordList %}
            {% if item.class %}
                <li class="active">{{ item.title }}</li>
            {% else %}
                <li class="{{ item.class }}"><a href="{{ item.url }}">{{ item.title }}</a></li>
            {% endif %}
        {% endfor %}
    </ol>
</div>

app_rbac/templates/rbac/change.html
{% extends 'layout.html' %}
{% block css %}
    <style>
        ul {
            list-style: none;
            padding: 0;
        }

        ul li {
            float: left;
            padding: 10px;
            padding-left: 0;
            width: 80px;
        }

        ul li i {
            font-size: 18px;
            margin-left: 5px;
            color: #66afe9;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="luffy-container">
        <form class="form-horizontal" method="post" novalidate>
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <label class="col-sm-2 control-label">{{ field.label }}</label>
                    <div class="col-sm-8">
                        {{ field }}
                        <span>{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-8">
                    <input type="submit" value=" 保 存 " class="btn btn-primary">
                </div>
            </div>
        </form>
    </div>
{% endblock %}

app_rbac/templates/rbac/delete.html
{% extends 'layout.html' %}

{% block content %}
    <div class="luffy-container">
        <div class="alert alert-danger" role="alert">
            <form method="post">
                {% csrf_token %}
                <p style="font-size: 13px;"><i class="fa fa-warning" aria-hidden="true"></i>删除后不可恢复，确认是否删除？</p>
                <div style="margin-top: 20px;">
                    <a href="{{ cancelUrl }}" class="btn btn-default btn-sm">取消</a>
                    <input type="submit" class="btn btn-danger btn-sm" value="确 认">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

app_rbac/templates/rbac/multiMenu.html
<!-- 左侧二级菜单展示 -->
<div class="multi-menu">
    {% for item in menuDict.values %}
        <div class="item">
            <div class="title"><span class="icon-warp"><i class="fa {{ item.icon }}"></i></span>{{ item.title }}</div>
            <div class="body {{ item.class }}">
                {% for per in item.children %}
                    <a href="{{ per.url }}" class="{{ per.class }}">{{ per.title }}</a>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
</div>

app_rbac/templates/rbac/multi_permission.html
{% extends 'layout.html' %}

{% block css %}
	<style>
        .error_show {
            position: fixed;
            top: 10%;
            left: 25%;
            width: 60%;
            height: 30%;
            background-color: #666;
            border: 1px solid red;
            border-radius: 10px;
            z-index: 9999;
        }

	</style>

{% endblock %}

{% block content %}
	<div class="luffy-container">
		<!-- 待增加的面板 -->
		<form method="post" action="?type=generate">
			{% csrf_token %}
			{{ generate_formset.management_form }}
			<div class="panel panel-default">
				<div class="panel-heading">
					<i class="fa fa-th-list" aria-hidden="true"></i>待新建的权限列表（只在项目中存在，数据库中没有的权限路由）
					<!-- 携带当前页面参数进入添加页面，然后再将当前参数携带回来，用于默认选中菜单的样式生成 -->
					<button href="#" class="right btn btn-primary btn-xs"
					        style="padding: 2px 8px;margin: -3px;">
						<i class="fa fa-save" aria-hidden="true"></i>
						新建
					</button>
				</div>
				<!-- Table -->
				<table class="table">
					<thead>
					<tr>
						<th>序号</th>
						<th>名称</th>
						<th>URL</th>
						<th>别名</th>
						<th>菜单</th>
						<th>父权限</th>
					</tr>
					</thead>
					<tbody>
					{% for form in generate_formset %}
						<tr>
							<td>{{ forloop.counter }}</td>
							{% for field in form %}
								<td>{{ field }} <span style="color: red;">{{ field.errors.0 }}</span></td>
							{% endfor %}
						</tr>
					{% endfor %}
					</tbody>
				</table>
			</div>
		</form>

		<!-- 待删除的面板 -->
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="fa fa-th-list" aria-hidden="true"></i>只在数据库存在的所有权限路由(不做批量删除，如果有需要跳转到站外的路由删除会导致功能的缺失)
			</div>
			<!-- Table -->
			<table class="table">
				<thead>
				<tr>
					<th>序号</th>
					<th>名称</th>
					<th>URL</th>
					<th>别名</th>
					<th>操作</th>
				</tr>
				</thead>
				<tbody>
				{% for row in delete_row_list %}
					<tr>
						<td>{{ forloop.counter }}</td>
						<td>{{ row.title }}</td>
						<td>{{ row.url }}</td>
						<td>{{ row.name }}</td>
						<td><a href="{% url 'rbac:multi_permissions_del' pk=row.id %}"
						       style="text-decoration: none;font-size: 16px;">
							<i class="fas fa-trash-alt"></i>
						</a></td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>

		<!-- 待更新的面板 -->
		<form method="post" action="?type=update">
			{% csrf_token %}
			{{ update_formset.management_form }}
			<div class="panel panel-default">
				<div class="panel-heading">
					<i class="fa fa-th-list" aria-hidden="true"></i>待更新的权限列表
					<!-- 携带当前页面参数进入添加页面，然后再将当前参数携带回来，用于默认选中菜单的样式生成 -->
					<button href="" class="right btn btn-primary btn-xs"
					        style="padding: 2px 8px;margin: -3px;">
						<i class="fa fa-save" aria-hidden="true"></i>
						保存
					</button>
				</div>

				<!-- Table -->
				<table class="table">
					<thead>
					<tr>
						<th>序号</th>
						<th>名称</th>
						<th>URL_ERROR</th>
						<th>URL</th>
						<th>别名</th>
						<th>菜单</th>
						<th>父权限</th>
					</tr>
					</thead>
					<tbody>
					{% for form in update_formset %}
						<tr>
							<td>{{ forloop.counter }}</td>
							{% for field in form %}
								{% if forloop.first %}
									{{ field }}
								{% else %}
									<td style="color: skyblue;">{{ field }} <span
											style="color: red;">{{ field.errors.0 }}</span></td>
								{% endif %}
							{% endfor %}
						</tr>
					{% endfor %}
					</tbody>
				</table>
			</div>
		</form>
	</div>
{% endblock %}
{% block js %}
	<script>
		function has_error(data) {
			alert(data);
		}
	</script>
{% endblock %}

app_rbac/templates/rbac/resetpwd.html
{% extends 'layout.html' %}


{% block content %}
	<h1 style="text-align: center;color: red;margin: 0 auto;">重置密码</h1>
	<form method="post">
		{% csrf_token %}
		<p class="input"><input type="text" class="form-control" placeholder="请输入新密码" name="password"></p>
		<p class="input"><input type="text" class="form-control" placeholder="请再次输入密码" name="resetpassword"></p>
		<p class="error">{{ errors }}</p>
		<input type="submit" class="form-control">
	</form>
{% endblock %}

app_rbac/templates/rbac/role_list.html
{% extends 'layout.html' %}

{% block content %}

    <div class="luffy-container">
        <div class="btn-group" style="margin: 5px 0">
            <a class="btn btn-default" href="{% url 'rbac:role_add' %}">
                <i class="fa fa-plus-square" aria-hidden="true"></i> 添加角色
            </a>

        </div>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>ID</th>
                <th>名称</th>
                <th>选项</th>
            </tr>
            </thead>
            <tbody>
            {% for row in roleQuerySet %}
                <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row.title }}</td>
                    <td>
                        <a style="color: #333333;" href="{% url 'rbac:role_edit' pk=row.id %}">
                            <i class="fa fa-edit" aria-hidden="true"></i></a>
                        <a style="color: #d9534f;" href="{% url 'rbac:role_del' pk=row.id %}"><i
                                class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

app_rbac/templates/rbac/staticMenu.html
<!-- 左侧一级菜单展示 -->
<div class="static-menu">
    {% for menu in menuList %}
        <a href="{{ menu.url }}">
            <span class="icon-wrap"><i class="fa {{ menu.icon }}"></i></span> {{ menu.title }}</a>
    {% endfor %}
</div>

app_rbac/templates/rbac/user_list.html
{% extends 'layout.html' %}

{% block content %}

    <div class="luffy-container">
        <div class="btn-group" style="margin: 5px 0">
            <a class="btn btn-default" href="{% url 'rbac:user_add' %}">
                <i class="fa fa-plus-square" aria-hidden="true"></i> 添加用户
            </a>

        </div>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>序号</th>
                <th>用户名</th>
                <th>邮箱</th>
                <th>重置密码</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for row in userQuerySet %}
                <tr>
                    <td>{{ forloop.counter }}</td>  {# 循环计数器 #}
                    <td>{{ row.name }}</td>
                    <td>{{ row.email }}</td>
                    <td><a href="{% url 'rbac:user_reset' pk=row.pk %}">重置</a></td>
                    <td>
                        <a style="color: #333333;" href="{% url 'rbac:user_edit' pk=row.id %}">
                            <i class="fa fa-edit" aria-hidden="true"></i></a>
                        <a style="color: #d9534f;" href="{% url 'rbac:user_del' pk=row.id %}"><i
                                class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}